apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      imagePullSecrets:
      {{- if .Values.imagePullSecrets }}
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      containers:
      {{- range .Values.containers }}
      - name: {{ .name }}
        image: "{{ .image.repository }}:{{ .image.tag }}"
        ports:
        - containerPort: {{ .port }}
        resources:
          requests:
            cpu: {{ $.Values.resources.requests.cpu }}
            memory: {{ $.Values.resources.requests.memory }}
          limits:
            memory: {{ $.Values.resources.limits.memory }}
        env:
        - name: NGINX_PORT
          value: "{{ .port }}"
        command:
        - /bin/sh
        - -c
        - |
          sed -i "s/listen 80;/listen ${NGINX_PORT};/" /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'
      {{- end }}
