name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Private Docker Hub Repo
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t abdulkyndryl/team-18-kc-hackathon:app2 .

    - name: Push Docker image to Private Repo
      run: docker push abdulkyndryl/team-18-kc-hackathon:app2
    
    - name: Install sshpass on VM
      run: sudo apt-get install -y sshpass

    # - name: Deploy Docker container on Linux VM
    #   run: |
    #     sshpass -p "${{ secrets.LINUX_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.LINUX_USER }}@${{ secrets.LINUX_HOST }} << EOF
    #     docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
    #     docker pull abdulkyndryl/team-18-kc-hackathon:latest
    #     docker stop team-18-container || true
    #     docker rm team-18-container || true
    #     docker run -d -p 80:80 --name team-18-container abdulkyndryl/team-18-kc-hackathon:latest
    #     EOF
    #   env:
    #     SSHPASS: ${{ secrets.LINUX_PASSWORD }}
